backend:
  name: git-gateway
  repo: sanampatel/staticpress-purecss-blog
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: source/images
collections:
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "source/_categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "source/_tags"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Author Name", name: "authorname", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "SEOTitle", name: "seotitle", widget: "string", default: "SEO Title", required: false}
      - {label: "SEO Keywords", name: "seokeywords", widget: "string", default: SEO Keywords, required: false}
      - {label: "SEO Description", name: "seodescription", widget: "string", default: SEO Description, required: false}
      - {label: "Tags", name: "tags", widget: "relation", collection: 'tags', searchFields: ["title"], displayFields: ["title"], valueField: "title", multiple: true, default: ""}
      - {label: "Categories", name: "categories", widget: "relation", collection: 'categories', searchFields: ["title"], displayFields: ["title"], valueField: "title", default: ""}
      - {label: "Image Filename", name: "image", widget: "image", required: true}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "IsPosts", name: "isPosts", widget: "hidden", default: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    label_singular: "Setting"
    folder: "source/_settings"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Setting"}
      - {label: "SEOTitle", name: "seotitle", widget: "string", default: "SEO Title", required: false}
      - {label: "SEO Keywords", name: "seokeywords", widget: "string", default: SEO Keywords, required: false}
      - {label: "SEO Description", name: "seodescription", widget: "string", default: SEO Description, required: false}
      - {label: "About author", name: "aboutauthor", widget: "markdown", default: "About author"}
      - {label: "Post page title", name: "postpagetitle", widget: "string", default: "Post page title", required: false}
      - {label: "Logo", name: "logo", markdown: "image"}
      - {label: "FbLink", name: "fblink", widget: "string", required: false}
      - {label: "TwitterLink:", name: "twitterlink", widget: "string", required: false}
      - {label: "InstagramLink", name: "instagramlink", widget: "string", required: false}
      - {label: "Custom Header", name: "customheader", widget: "markdown", required: false}
      - {label: "Custom Footer", name: "customfooter", widget: "markdown", required: false}